services:
  - type: web
    name: bitespeed-identity
    env: node
    buildCommand: npm install && npm run build && npx prisma generate && npx prisma db push
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: bitespeed-db
          property: connectionString

databases:
  - name: bitespeed-db
    engine: postgres
    version: 15
    plan: free
    initialDatabase: bitespeed
